root: true
ignorePatterns:
  - jest.config.js
  - next.config.js
parserOptions:
  project: ./tsconfig.eslint.json
extends:
  - 'airbnb'
  - 'airbnb-typescript'
  # next/core-web-vitalsはnextを包含している？
  - 'next'
  - 'next/core-web-vitals'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:import/typescript'
  - 'plugin:jest/recommended'
  - 'plugin:jest-dom/recommended'
  - 'plugin:storybook/recommended'
  - 'prettier'
plugins:
  - 'jest'
  - 'jest-dom'
rules:
  eqeqeq:
    - error
    - always
  no-eval:
    - error
  no-implicit-globals:
    - error
  no-multi-spaces:
    - error
  prefer-const: error
  no-use-before-define: error
  no-var: error

  #jsx-a11y
  jsx-a11y/label-has-associated-control: 'off'

  # import rules
  import/order:
    - error
    - newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  import/prefer-default-export:
    - off
  import/extensions:
    - off
  import/no-extraneous-dependencies:
    - 'error'
    - devDependencies:
        - '**/*.stories.*'
      peerDependencies: true

  # react rules
  react/jsx-filename-extension:
    - 1
    - extensions:
        - '.jsx'
        - '.tsx'
  react/jsx-props-no-spreading: 'off'
  react/function-component-definition: 'off'
  prefer-arrow-callback: 'off'
  react/require-default-props: 'off'
